### ISSUE TITLE
Change example to match ansible example

### ISSUE THREAD

**Issue by dyegoe** [dyegoe/terraform-libvirt#6]
Change the example to match the 3 instances that `ansible-k8s-cluster` has as an example

```yaml
---
all:
  vars:
    ansible_user: ubuntu
  children:
    masters:
      hosts:
        master:
          ansible_host: 10.100.200.2
    nodes:
      hosts:
        node01:
          ansible_host: 10.100.200.3
        node02:
          ansible_host: 10.100.200.4
```
